// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: dbmanagement_ordermanagement.proto

#include "dbmanagement_ordermanagement.pb.h"
#include "dbmanagement_ordermanagement.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace grpc_dbmanagement {

static const char* DBManagement_OrderManagement_Service_method_names[] = {
  "/grpc_dbmanagement.DBManagement_OrderManagement_Service/Insert",
};

std::unique_ptr< DBManagement_OrderManagement_Service::Stub> DBManagement_OrderManagement_Service::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< DBManagement_OrderManagement_Service::Stub> stub(new DBManagement_OrderManagement_Service::Stub(channel));
  return stub;
}

DBManagement_OrderManagement_Service::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_Insert_(DBManagement_OrderManagement_Service_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status DBManagement_OrderManagement_Service::Stub::Insert(::grpc::ClientContext* context, const ::grpc_dbmanagement::Request_Insert& request, ::grpc_dbmanagement::Reply_Insert* response) {
  return ::grpc::internal::BlockingUnaryCall< ::grpc_dbmanagement::Request_Insert, ::grpc_dbmanagement::Reply_Insert, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Insert_, context, request, response);
}

void DBManagement_OrderManagement_Service::Stub::experimental_async::Insert(::grpc::ClientContext* context, const ::grpc_dbmanagement::Request_Insert* request, ::grpc_dbmanagement::Reply_Insert* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::grpc_dbmanagement::Request_Insert, ::grpc_dbmanagement::Reply_Insert, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Insert_, context, request, response, std::move(f));
}

void DBManagement_OrderManagement_Service::Stub::experimental_async::Insert(::grpc::ClientContext* context, const ::grpc_dbmanagement::Request_Insert* request, ::grpc_dbmanagement::Reply_Insert* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Insert_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::grpc_dbmanagement::Reply_Insert>* DBManagement_OrderManagement_Service::Stub::PrepareAsyncInsertRaw(::grpc::ClientContext* context, const ::grpc_dbmanagement::Request_Insert& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::grpc_dbmanagement::Reply_Insert, ::grpc_dbmanagement::Request_Insert, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Insert_, context, request);
}

::grpc::ClientAsyncResponseReader< ::grpc_dbmanagement::Reply_Insert>* DBManagement_OrderManagement_Service::Stub::AsyncInsertRaw(::grpc::ClientContext* context, const ::grpc_dbmanagement::Request_Insert& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncInsertRaw(context, request, cq);
  result->StartCall();
  return result;
}

DBManagement_OrderManagement_Service::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DBManagement_OrderManagement_Service_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< DBManagement_OrderManagement_Service::Service, ::grpc_dbmanagement::Request_Insert, ::grpc_dbmanagement::Reply_Insert, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](DBManagement_OrderManagement_Service::Service* service,
             ::grpc::ServerContext* ctx,
             const ::grpc_dbmanagement::Request_Insert* req,
             ::grpc_dbmanagement::Reply_Insert* resp) {
               return service->Insert(ctx, req, resp);
             }, this)));
}

DBManagement_OrderManagement_Service::Service::~Service() {
}

::grpc::Status DBManagement_OrderManagement_Service::Service::Insert(::grpc::ServerContext* context, const ::grpc_dbmanagement::Request_Insert* request, ::grpc_dbmanagement::Reply_Insert* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace grpc_dbmanagement

