// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dbmanagement_ordermanagement.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_dbmanagement_5fordermanagement_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_dbmanagement_5fordermanagement_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3015000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3015002 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_dbmanagement_5fordermanagement_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_dbmanagement_5fordermanagement_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[4]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_dbmanagement_5fordermanagement_2eproto;
::PROTOBUF_NAMESPACE_ID::Metadata descriptor_table_dbmanagement_5fordermanagement_2eproto_metadata_getter(int index);
namespace grpc_dbmanagement {
class Reply_Insert;
struct Reply_InsertDefaultTypeInternal;
extern Reply_InsertDefaultTypeInternal _Reply_Insert_default_instance_;
class Request_Insert;
struct Request_InsertDefaultTypeInternal;
extern Request_InsertDefaultTypeInternal _Request_Insert_default_instance_;
class Request_Insert_Goods_Info;
struct Request_Insert_Goods_InfoDefaultTypeInternal;
extern Request_Insert_Goods_InfoDefaultTypeInternal _Request_Insert_Goods_Info_default_instance_;
class Request_Insert_Order_Data;
struct Request_Insert_Order_DataDefaultTypeInternal;
extern Request_Insert_Order_DataDefaultTypeInternal _Request_Insert_Order_Data_default_instance_;
}  // namespace grpc_dbmanagement
PROTOBUF_NAMESPACE_OPEN
template<> ::grpc_dbmanagement::Reply_Insert* Arena::CreateMaybeMessage<::grpc_dbmanagement::Reply_Insert>(Arena*);
template<> ::grpc_dbmanagement::Request_Insert* Arena::CreateMaybeMessage<::grpc_dbmanagement::Request_Insert>(Arena*);
template<> ::grpc_dbmanagement::Request_Insert_Goods_Info* Arena::CreateMaybeMessage<::grpc_dbmanagement::Request_Insert_Goods_Info>(Arena*);
template<> ::grpc_dbmanagement::Request_Insert_Order_Data* Arena::CreateMaybeMessage<::grpc_dbmanagement::Request_Insert_Order_Data>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace grpc_dbmanagement {

// ===================================================================

class Request_Insert_Goods_Info PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:grpc_dbmanagement.Request_Insert.Goods_Info) */ {
 public:
  inline Request_Insert_Goods_Info() : Request_Insert_Goods_Info(nullptr) {}
  virtual ~Request_Insert_Goods_Info();
  explicit constexpr Request_Insert_Goods_Info(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Request_Insert_Goods_Info(const Request_Insert_Goods_Info& from);
  Request_Insert_Goods_Info(Request_Insert_Goods_Info&& from) noexcept
    : Request_Insert_Goods_Info() {
    *this = ::std::move(from);
  }

  inline Request_Insert_Goods_Info& operator=(const Request_Insert_Goods_Info& from) {
    CopyFrom(from);
    return *this;
  }
  inline Request_Insert_Goods_Info& operator=(Request_Insert_Goods_Info&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Request_Insert_Goods_Info& default_instance() {
    return *internal_default_instance();
  }
  static inline const Request_Insert_Goods_Info* internal_default_instance() {
    return reinterpret_cast<const Request_Insert_Goods_Info*>(
               &_Request_Insert_Goods_Info_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Request_Insert_Goods_Info& a, Request_Insert_Goods_Info& b) {
    a.Swap(&b);
  }
  inline void Swap(Request_Insert_Goods_Info* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Request_Insert_Goods_Info* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Request_Insert_Goods_Info* New() const final {
    return CreateMaybeMessage<Request_Insert_Goods_Info>(nullptr);
  }

  Request_Insert_Goods_Info* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Request_Insert_Goods_Info>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Request_Insert_Goods_Info& from);
  void MergeFrom(const Request_Insert_Goods_Info& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Request_Insert_Goods_Info* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "grpc_dbmanagement.Request_Insert.Goods_Info";
  }
  protected:
  explicit Request_Insert_Goods_Info(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_dbmanagement_5fordermanagement_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 1,
  };
  // string name = 1;
  bool has_name() const;
  private:
  bool _internal_has_name() const;
  public:
  void clear_name();
  const std::string& name() const;
  void set_name(const std::string& value);
  void set_name(std::string&& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  std::string* mutable_name();
  std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // @@protoc_insertion_point(class_scope:grpc_dbmanagement.Request_Insert.Goods_Info)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  friend struct ::TableStruct_dbmanagement_5fordermanagement_2eproto;
};
// -------------------------------------------------------------------

class Request_Insert_Order_Data PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:grpc_dbmanagement.Request_Insert.Order_Data) */ {
 public:
  inline Request_Insert_Order_Data() : Request_Insert_Order_Data(nullptr) {}
  virtual ~Request_Insert_Order_Data();
  explicit constexpr Request_Insert_Order_Data(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Request_Insert_Order_Data(const Request_Insert_Order_Data& from);
  Request_Insert_Order_Data(Request_Insert_Order_Data&& from) noexcept
    : Request_Insert_Order_Data() {
    *this = ::std::move(from);
  }

  inline Request_Insert_Order_Data& operator=(const Request_Insert_Order_Data& from) {
    CopyFrom(from);
    return *this;
  }
  inline Request_Insert_Order_Data& operator=(Request_Insert_Order_Data&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Request_Insert_Order_Data& default_instance() {
    return *internal_default_instance();
  }
  static inline const Request_Insert_Order_Data* internal_default_instance() {
    return reinterpret_cast<const Request_Insert_Order_Data*>(
               &_Request_Insert_Order_Data_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Request_Insert_Order_Data& a, Request_Insert_Order_Data& b) {
    a.Swap(&b);
  }
  inline void Swap(Request_Insert_Order_Data* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Request_Insert_Order_Data* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Request_Insert_Order_Data* New() const final {
    return CreateMaybeMessage<Request_Insert_Order_Data>(nullptr);
  }

  Request_Insert_Order_Data* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Request_Insert_Order_Data>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Request_Insert_Order_Data& from);
  void MergeFrom(const Request_Insert_Order_Data& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Request_Insert_Order_Data* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "grpc_dbmanagement.Request_Insert.Order_Data";
  }
  protected:
  explicit Request_Insert_Order_Data(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_dbmanagement_5fordermanagement_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kGoodsInfoFieldNumber = 1,
    kGoodsPosFieldNumber = 2,
    kTargetPosFieldNumber = 3,
  };
  // .grpc_dbmanagement.Request_Insert.Goods_Info goods_info = 1;
  bool has_goods_info() const;
  private:
  bool _internal_has_goods_info() const;
  public:
  void clear_goods_info();
  const ::grpc_dbmanagement::Request_Insert_Goods_Info& goods_info() const;
  ::grpc_dbmanagement::Request_Insert_Goods_Info* release_goods_info();
  ::grpc_dbmanagement::Request_Insert_Goods_Info* mutable_goods_info();
  void set_allocated_goods_info(::grpc_dbmanagement::Request_Insert_Goods_Info* goods_info);
  private:
  const ::grpc_dbmanagement::Request_Insert_Goods_Info& _internal_goods_info() const;
  ::grpc_dbmanagement::Request_Insert_Goods_Info* _internal_mutable_goods_info();
  public:
  void unsafe_arena_set_allocated_goods_info(
      ::grpc_dbmanagement::Request_Insert_Goods_Info* goods_info);
  ::grpc_dbmanagement::Request_Insert_Goods_Info* unsafe_arena_release_goods_info();

  // int32 goods_pos = 2;
  bool has_goods_pos() const;
  private:
  bool _internal_has_goods_pos() const;
  public:
  void clear_goods_pos();
  ::PROTOBUF_NAMESPACE_ID::int32 goods_pos() const;
  void set_goods_pos(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_goods_pos() const;
  void _internal_set_goods_pos(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 target_pos = 3;
  bool has_target_pos() const;
  private:
  bool _internal_has_target_pos() const;
  public:
  void clear_target_pos();
  ::PROTOBUF_NAMESPACE_ID::int32 target_pos() const;
  void set_target_pos(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_target_pos() const;
  void _internal_set_target_pos(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:grpc_dbmanagement.Request_Insert.Order_Data)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::grpc_dbmanagement::Request_Insert_Goods_Info* goods_info_;
  ::PROTOBUF_NAMESPACE_ID::int32 goods_pos_;
  ::PROTOBUF_NAMESPACE_ID::int32 target_pos_;
  friend struct ::TableStruct_dbmanagement_5fordermanagement_2eproto;
};
// -------------------------------------------------------------------

class Request_Insert PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:grpc_dbmanagement.Request_Insert) */ {
 public:
  inline Request_Insert() : Request_Insert(nullptr) {}
  virtual ~Request_Insert();
  explicit constexpr Request_Insert(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Request_Insert(const Request_Insert& from);
  Request_Insert(Request_Insert&& from) noexcept
    : Request_Insert() {
    *this = ::std::move(from);
  }

  inline Request_Insert& operator=(const Request_Insert& from) {
    CopyFrom(from);
    return *this;
  }
  inline Request_Insert& operator=(Request_Insert&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Request_Insert& default_instance() {
    return *internal_default_instance();
  }
  static inline const Request_Insert* internal_default_instance() {
    return reinterpret_cast<const Request_Insert*>(
               &_Request_Insert_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Request_Insert& a, Request_Insert& b) {
    a.Swap(&b);
  }
  inline void Swap(Request_Insert* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Request_Insert* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Request_Insert* New() const final {
    return CreateMaybeMessage<Request_Insert>(nullptr);
  }

  Request_Insert* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Request_Insert>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Request_Insert& from);
  void MergeFrom(const Request_Insert& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Request_Insert* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "grpc_dbmanagement.Request_Insert";
  }
  protected:
  explicit Request_Insert(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_dbmanagement_5fordermanagement_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  typedef Request_Insert_Goods_Info Goods_Info;
  typedef Request_Insert_Order_Data Order_Data;

  // accessors -------------------------------------------------------

  enum : int {
    kTypeFieldNumber = 4,
    kResultFieldNumber = 5,
    kDataFieldNumber = 3,
    kNumberFieldNumber = 1,
    kTimeFieldNumber = 2,
  };
  // string type = 4;
  bool has_type() const;
  private:
  bool _internal_has_type() const;
  public:
  void clear_type();
  const std::string& type() const;
  void set_type(const std::string& value);
  void set_type(std::string&& value);
  void set_type(const char* value);
  void set_type(const char* value, size_t size);
  std::string* mutable_type();
  std::string* release_type();
  void set_allocated_type(std::string* type);
  private:
  const std::string& _internal_type() const;
  void _internal_set_type(const std::string& value);
  std::string* _internal_mutable_type();
  public:

  // string result = 5;
  bool has_result() const;
  private:
  bool _internal_has_result() const;
  public:
  void clear_result();
  const std::string& result() const;
  void set_result(const std::string& value);
  void set_result(std::string&& value);
  void set_result(const char* value);
  void set_result(const char* value, size_t size);
  std::string* mutable_result();
  std::string* release_result();
  void set_allocated_result(std::string* result);
  private:
  const std::string& _internal_result() const;
  void _internal_set_result(const std::string& value);
  std::string* _internal_mutable_result();
  public:

  // .grpc_dbmanagement.Request_Insert.Order_Data data = 3;
  bool has_data() const;
  private:
  bool _internal_has_data() const;
  public:
  void clear_data();
  const ::grpc_dbmanagement::Request_Insert_Order_Data& data() const;
  ::grpc_dbmanagement::Request_Insert_Order_Data* release_data();
  ::grpc_dbmanagement::Request_Insert_Order_Data* mutable_data();
  void set_allocated_data(::grpc_dbmanagement::Request_Insert_Order_Data* data);
  private:
  const ::grpc_dbmanagement::Request_Insert_Order_Data& _internal_data() const;
  ::grpc_dbmanagement::Request_Insert_Order_Data* _internal_mutable_data();
  public:
  void unsafe_arena_set_allocated_data(
      ::grpc_dbmanagement::Request_Insert_Order_Data* data);
  ::grpc_dbmanagement::Request_Insert_Order_Data* unsafe_arena_release_data();

  // int32 number = 1;
  bool has_number() const;
  private:
  bool _internal_has_number() const;
  public:
  void clear_number();
  ::PROTOBUF_NAMESPACE_ID::int32 number() const;
  void set_number(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_number() const;
  void _internal_set_number(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 time = 2;
  bool has_time() const;
  private:
  bool _internal_has_time() const;
  public:
  void clear_time();
  ::PROTOBUF_NAMESPACE_ID::int32 time() const;
  void set_time(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_time() const;
  void _internal_set_time(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:grpc_dbmanagement.Request_Insert)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr type_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr result_;
  ::grpc_dbmanagement::Request_Insert_Order_Data* data_;
  ::PROTOBUF_NAMESPACE_ID::int32 number_;
  ::PROTOBUF_NAMESPACE_ID::int32 time_;
  friend struct ::TableStruct_dbmanagement_5fordermanagement_2eproto;
};
// -------------------------------------------------------------------

class Reply_Insert PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:grpc_dbmanagement.Reply_Insert) */ {
 public:
  inline Reply_Insert() : Reply_Insert(nullptr) {}
  virtual ~Reply_Insert();
  explicit constexpr Reply_Insert(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Reply_Insert(const Reply_Insert& from);
  Reply_Insert(Reply_Insert&& from) noexcept
    : Reply_Insert() {
    *this = ::std::move(from);
  }

  inline Reply_Insert& operator=(const Reply_Insert& from) {
    CopyFrom(from);
    return *this;
  }
  inline Reply_Insert& operator=(Reply_Insert&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Reply_Insert& default_instance() {
    return *internal_default_instance();
  }
  static inline const Reply_Insert* internal_default_instance() {
    return reinterpret_cast<const Reply_Insert*>(
               &_Reply_Insert_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(Reply_Insert& a, Reply_Insert& b) {
    a.Swap(&b);
  }
  inline void Swap(Reply_Insert* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Reply_Insert* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Reply_Insert* New() const final {
    return CreateMaybeMessage<Reply_Insert>(nullptr);
  }

  Reply_Insert* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Reply_Insert>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Reply_Insert& from);
  void MergeFrom(const Reply_Insert& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Reply_Insert* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "grpc_dbmanagement.Reply_Insert";
  }
  protected:
  explicit Reply_Insert(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_dbmanagement_5fordermanagement_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kInsertResultFieldNumber = 1,
  };
  // bool insert_result = 1;
  bool has_insert_result() const;
  private:
  bool _internal_has_insert_result() const;
  public:
  void clear_insert_result();
  bool insert_result() const;
  void set_insert_result(bool value);
  private:
  bool _internal_insert_result() const;
  void _internal_set_insert_result(bool value);
  public:

  // @@protoc_insertion_point(class_scope:grpc_dbmanagement.Reply_Insert)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  bool insert_result_;
  friend struct ::TableStruct_dbmanagement_5fordermanagement_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Request_Insert_Goods_Info

// string name = 1;
inline bool Request_Insert_Goods_Info::_internal_has_name() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool Request_Insert_Goods_Info::has_name() const {
  return _internal_has_name();
}
inline void Request_Insert_Goods_Info::clear_name() {
  name_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& Request_Insert_Goods_Info::name() const {
  // @@protoc_insertion_point(field_get:grpc_dbmanagement.Request_Insert.Goods_Info.name)
  return _internal_name();
}
inline void Request_Insert_Goods_Info::set_name(const std::string& value) {
  _internal_set_name(value);
  // @@protoc_insertion_point(field_set:grpc_dbmanagement.Request_Insert.Goods_Info.name)
}
inline std::string* Request_Insert_Goods_Info::mutable_name() {
  // @@protoc_insertion_point(field_mutable:grpc_dbmanagement.Request_Insert.Goods_Info.name)
  return _internal_mutable_name();
}
inline const std::string& Request_Insert_Goods_Info::_internal_name() const {
  return name_.Get();
}
inline void Request_Insert_Goods_Info::_internal_set_name(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void Request_Insert_Goods_Info::set_name(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  name_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:grpc_dbmanagement.Request_Insert.Goods_Info.name)
}
inline void Request_Insert_Goods_Info::set_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:grpc_dbmanagement.Request_Insert.Goods_Info.name)
}
inline void Request_Insert_Goods_Info::set_name(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000001u;
  name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:grpc_dbmanagement.Request_Insert.Goods_Info.name)
}
inline std::string* Request_Insert_Goods_Info::_internal_mutable_name() {
  _has_bits_[0] |= 0x00000001u;
  return name_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* Request_Insert_Goods_Info::release_name() {
  // @@protoc_insertion_point(field_release:grpc_dbmanagement.Request_Insert.Goods_Info.name)
  if (!_internal_has_name()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return name_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void Request_Insert_Goods_Info::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:grpc_dbmanagement.Request_Insert.Goods_Info.name)
}

// -------------------------------------------------------------------

// Request_Insert_Order_Data

// .grpc_dbmanagement.Request_Insert.Goods_Info goods_info = 1;
inline bool Request_Insert_Order_Data::_internal_has_goods_info() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || goods_info_ != nullptr);
  return value;
}
inline bool Request_Insert_Order_Data::has_goods_info() const {
  return _internal_has_goods_info();
}
inline void Request_Insert_Order_Data::clear_goods_info() {
  if (GetArena() == nullptr && goods_info_ != nullptr) {
    delete goods_info_;
  }
  goods_info_ = nullptr;
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::grpc_dbmanagement::Request_Insert_Goods_Info& Request_Insert_Order_Data::_internal_goods_info() const {
  const ::grpc_dbmanagement::Request_Insert_Goods_Info* p = goods_info_;
  return p != nullptr ? *p : reinterpret_cast<const ::grpc_dbmanagement::Request_Insert_Goods_Info&>(
      ::grpc_dbmanagement::_Request_Insert_Goods_Info_default_instance_);
}
inline const ::grpc_dbmanagement::Request_Insert_Goods_Info& Request_Insert_Order_Data::goods_info() const {
  // @@protoc_insertion_point(field_get:grpc_dbmanagement.Request_Insert.Order_Data.goods_info)
  return _internal_goods_info();
}
inline void Request_Insert_Order_Data::unsafe_arena_set_allocated_goods_info(
    ::grpc_dbmanagement::Request_Insert_Goods_Info* goods_info) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(goods_info_);
  }
  goods_info_ = goods_info;
  if (goods_info) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:grpc_dbmanagement.Request_Insert.Order_Data.goods_info)
}
inline ::grpc_dbmanagement::Request_Insert_Goods_Info* Request_Insert_Order_Data::release_goods_info() {
  _has_bits_[0] &= ~0x00000001u;
  ::grpc_dbmanagement::Request_Insert_Goods_Info* temp = goods_info_;
  goods_info_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::grpc_dbmanagement::Request_Insert_Goods_Info* Request_Insert_Order_Data::unsafe_arena_release_goods_info() {
  // @@protoc_insertion_point(field_release:grpc_dbmanagement.Request_Insert.Order_Data.goods_info)
  _has_bits_[0] &= ~0x00000001u;
  ::grpc_dbmanagement::Request_Insert_Goods_Info* temp = goods_info_;
  goods_info_ = nullptr;
  return temp;
}
inline ::grpc_dbmanagement::Request_Insert_Goods_Info* Request_Insert_Order_Data::_internal_mutable_goods_info() {
  _has_bits_[0] |= 0x00000001u;
  if (goods_info_ == nullptr) {
    auto* p = CreateMaybeMessage<::grpc_dbmanagement::Request_Insert_Goods_Info>(GetArena());
    goods_info_ = p;
  }
  return goods_info_;
}
inline ::grpc_dbmanagement::Request_Insert_Goods_Info* Request_Insert_Order_Data::mutable_goods_info() {
  // @@protoc_insertion_point(field_mutable:grpc_dbmanagement.Request_Insert.Order_Data.goods_info)
  return _internal_mutable_goods_info();
}
inline void Request_Insert_Order_Data::set_allocated_goods_info(::grpc_dbmanagement::Request_Insert_Goods_Info* goods_info) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete goods_info_;
  }
  if (goods_info) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(goods_info);
    if (message_arena != submessage_arena) {
      goods_info = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, goods_info, submessage_arena);
    }
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  goods_info_ = goods_info;
  // @@protoc_insertion_point(field_set_allocated:grpc_dbmanagement.Request_Insert.Order_Data.goods_info)
}

// int32 goods_pos = 2;
inline bool Request_Insert_Order_Data::_internal_has_goods_pos() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool Request_Insert_Order_Data::has_goods_pos() const {
  return _internal_has_goods_pos();
}
inline void Request_Insert_Order_Data::clear_goods_pos() {
  goods_pos_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Request_Insert_Order_Data::_internal_goods_pos() const {
  return goods_pos_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Request_Insert_Order_Data::goods_pos() const {
  // @@protoc_insertion_point(field_get:grpc_dbmanagement.Request_Insert.Order_Data.goods_pos)
  return _internal_goods_pos();
}
inline void Request_Insert_Order_Data::_internal_set_goods_pos(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000002u;
  goods_pos_ = value;
}
inline void Request_Insert_Order_Data::set_goods_pos(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_goods_pos(value);
  // @@protoc_insertion_point(field_set:grpc_dbmanagement.Request_Insert.Order_Data.goods_pos)
}

// int32 target_pos = 3;
inline bool Request_Insert_Order_Data::_internal_has_target_pos() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool Request_Insert_Order_Data::has_target_pos() const {
  return _internal_has_target_pos();
}
inline void Request_Insert_Order_Data::clear_target_pos() {
  target_pos_ = 0;
  _has_bits_[0] &= ~0x00000004u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Request_Insert_Order_Data::_internal_target_pos() const {
  return target_pos_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Request_Insert_Order_Data::target_pos() const {
  // @@protoc_insertion_point(field_get:grpc_dbmanagement.Request_Insert.Order_Data.target_pos)
  return _internal_target_pos();
}
inline void Request_Insert_Order_Data::_internal_set_target_pos(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000004u;
  target_pos_ = value;
}
inline void Request_Insert_Order_Data::set_target_pos(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_target_pos(value);
  // @@protoc_insertion_point(field_set:grpc_dbmanagement.Request_Insert.Order_Data.target_pos)
}

// -------------------------------------------------------------------

// Request_Insert

// int32 number = 1;
inline bool Request_Insert::_internal_has_number() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool Request_Insert::has_number() const {
  return _internal_has_number();
}
inline void Request_Insert::clear_number() {
  number_ = 0;
  _has_bits_[0] &= ~0x00000008u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Request_Insert::_internal_number() const {
  return number_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Request_Insert::number() const {
  // @@protoc_insertion_point(field_get:grpc_dbmanagement.Request_Insert.number)
  return _internal_number();
}
inline void Request_Insert::_internal_set_number(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000008u;
  number_ = value;
}
inline void Request_Insert::set_number(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_number(value);
  // @@protoc_insertion_point(field_set:grpc_dbmanagement.Request_Insert.number)
}

// int32 time = 2;
inline bool Request_Insert::_internal_has_time() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool Request_Insert::has_time() const {
  return _internal_has_time();
}
inline void Request_Insert::clear_time() {
  time_ = 0;
  _has_bits_[0] &= ~0x00000010u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Request_Insert::_internal_time() const {
  return time_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Request_Insert::time() const {
  // @@protoc_insertion_point(field_get:grpc_dbmanagement.Request_Insert.time)
  return _internal_time();
}
inline void Request_Insert::_internal_set_time(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000010u;
  time_ = value;
}
inline void Request_Insert::set_time(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_time(value);
  // @@protoc_insertion_point(field_set:grpc_dbmanagement.Request_Insert.time)
}

// .grpc_dbmanagement.Request_Insert.Order_Data data = 3;
inline bool Request_Insert::_internal_has_data() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  PROTOBUF_ASSUME(!value || data_ != nullptr);
  return value;
}
inline bool Request_Insert::has_data() const {
  return _internal_has_data();
}
inline void Request_Insert::clear_data() {
  if (GetArena() == nullptr && data_ != nullptr) {
    delete data_;
  }
  data_ = nullptr;
  _has_bits_[0] &= ~0x00000004u;
}
inline const ::grpc_dbmanagement::Request_Insert_Order_Data& Request_Insert::_internal_data() const {
  const ::grpc_dbmanagement::Request_Insert_Order_Data* p = data_;
  return p != nullptr ? *p : reinterpret_cast<const ::grpc_dbmanagement::Request_Insert_Order_Data&>(
      ::grpc_dbmanagement::_Request_Insert_Order_Data_default_instance_);
}
inline const ::grpc_dbmanagement::Request_Insert_Order_Data& Request_Insert::data() const {
  // @@protoc_insertion_point(field_get:grpc_dbmanagement.Request_Insert.data)
  return _internal_data();
}
inline void Request_Insert::unsafe_arena_set_allocated_data(
    ::grpc_dbmanagement::Request_Insert_Order_Data* data) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(data_);
  }
  data_ = data;
  if (data) {
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:grpc_dbmanagement.Request_Insert.data)
}
inline ::grpc_dbmanagement::Request_Insert_Order_Data* Request_Insert::release_data() {
  _has_bits_[0] &= ~0x00000004u;
  ::grpc_dbmanagement::Request_Insert_Order_Data* temp = data_;
  data_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::grpc_dbmanagement::Request_Insert_Order_Data* Request_Insert::unsafe_arena_release_data() {
  // @@protoc_insertion_point(field_release:grpc_dbmanagement.Request_Insert.data)
  _has_bits_[0] &= ~0x00000004u;
  ::grpc_dbmanagement::Request_Insert_Order_Data* temp = data_;
  data_ = nullptr;
  return temp;
}
inline ::grpc_dbmanagement::Request_Insert_Order_Data* Request_Insert::_internal_mutable_data() {
  _has_bits_[0] |= 0x00000004u;
  if (data_ == nullptr) {
    auto* p = CreateMaybeMessage<::grpc_dbmanagement::Request_Insert_Order_Data>(GetArena());
    data_ = p;
  }
  return data_;
}
inline ::grpc_dbmanagement::Request_Insert_Order_Data* Request_Insert::mutable_data() {
  // @@protoc_insertion_point(field_mutable:grpc_dbmanagement.Request_Insert.data)
  return _internal_mutable_data();
}
inline void Request_Insert::set_allocated_data(::grpc_dbmanagement::Request_Insert_Order_Data* data) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete data_;
  }
  if (data) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(data);
    if (message_arena != submessage_arena) {
      data = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, data, submessage_arena);
    }
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  data_ = data;
  // @@protoc_insertion_point(field_set_allocated:grpc_dbmanagement.Request_Insert.data)
}

// string type = 4;
inline bool Request_Insert::_internal_has_type() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool Request_Insert::has_type() const {
  return _internal_has_type();
}
inline void Request_Insert::clear_type() {
  type_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& Request_Insert::type() const {
  // @@protoc_insertion_point(field_get:grpc_dbmanagement.Request_Insert.type)
  return _internal_type();
}
inline void Request_Insert::set_type(const std::string& value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:grpc_dbmanagement.Request_Insert.type)
}
inline std::string* Request_Insert::mutable_type() {
  // @@protoc_insertion_point(field_mutable:grpc_dbmanagement.Request_Insert.type)
  return _internal_mutable_type();
}
inline const std::string& Request_Insert::_internal_type() const {
  return type_.Get();
}
inline void Request_Insert::_internal_set_type(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  type_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void Request_Insert::set_type(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  type_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:grpc_dbmanagement.Request_Insert.type)
}
inline void Request_Insert::set_type(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  type_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:grpc_dbmanagement.Request_Insert.type)
}
inline void Request_Insert::set_type(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000001u;
  type_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:grpc_dbmanagement.Request_Insert.type)
}
inline std::string* Request_Insert::_internal_mutable_type() {
  _has_bits_[0] |= 0x00000001u;
  return type_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* Request_Insert::release_type() {
  // @@protoc_insertion_point(field_release:grpc_dbmanagement.Request_Insert.type)
  if (!_internal_has_type()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return type_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void Request_Insert::set_allocated_type(std::string* type) {
  if (type != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  type_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), type,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:grpc_dbmanagement.Request_Insert.type)
}

// string result = 5;
inline bool Request_Insert::_internal_has_result() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool Request_Insert::has_result() const {
  return _internal_has_result();
}
inline void Request_Insert::clear_result() {
  result_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000002u;
}
inline const std::string& Request_Insert::result() const {
  // @@protoc_insertion_point(field_get:grpc_dbmanagement.Request_Insert.result)
  return _internal_result();
}
inline void Request_Insert::set_result(const std::string& value) {
  _internal_set_result(value);
  // @@protoc_insertion_point(field_set:grpc_dbmanagement.Request_Insert.result)
}
inline std::string* Request_Insert::mutable_result() {
  // @@protoc_insertion_point(field_mutable:grpc_dbmanagement.Request_Insert.result)
  return _internal_mutable_result();
}
inline const std::string& Request_Insert::_internal_result() const {
  return result_.Get();
}
inline void Request_Insert::_internal_set_result(const std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  result_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void Request_Insert::set_result(std::string&& value) {
  _has_bits_[0] |= 0x00000002u;
  result_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:grpc_dbmanagement.Request_Insert.result)
}
inline void Request_Insert::set_result(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000002u;
  result_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:grpc_dbmanagement.Request_Insert.result)
}
inline void Request_Insert::set_result(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000002u;
  result_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:grpc_dbmanagement.Request_Insert.result)
}
inline std::string* Request_Insert::_internal_mutable_result() {
  _has_bits_[0] |= 0x00000002u;
  return result_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* Request_Insert::release_result() {
  // @@protoc_insertion_point(field_release:grpc_dbmanagement.Request_Insert.result)
  if (!_internal_has_result()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  return result_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void Request_Insert::set_allocated_result(std::string* result) {
  if (result != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  result_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), result,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:grpc_dbmanagement.Request_Insert.result)
}

// -------------------------------------------------------------------

// Reply_Insert

// bool insert_result = 1;
inline bool Reply_Insert::_internal_has_insert_result() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool Reply_Insert::has_insert_result() const {
  return _internal_has_insert_result();
}
inline void Reply_Insert::clear_insert_result() {
  insert_result_ = false;
  _has_bits_[0] &= ~0x00000001u;
}
inline bool Reply_Insert::_internal_insert_result() const {
  return insert_result_;
}
inline bool Reply_Insert::insert_result() const {
  // @@protoc_insertion_point(field_get:grpc_dbmanagement.Reply_Insert.insert_result)
  return _internal_insert_result();
}
inline void Reply_Insert::_internal_set_insert_result(bool value) {
  _has_bits_[0] |= 0x00000001u;
  insert_result_ = value;
}
inline void Reply_Insert::set_insert_result(bool value) {
  _internal_set_insert_result(value);
  // @@protoc_insertion_point(field_set:grpc_dbmanagement.Reply_Insert.insert_result)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace grpc_dbmanagement

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_dbmanagement_5fordermanagement_2eproto
