// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: ordermanagement_jobmanagement.proto
#ifndef GRPC_ordermanagement_5fjobmanagement_2eproto__INCLUDED
#define GRPC_ordermanagement_5fjobmanagement_2eproto__INCLUDED

#include "ordermanagement_jobmanagement.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc_ordermanagement {

class OrderManagement_JobManagement_Service final {
 public:
  static constexpr char const* service_full_name() {
    return "grpc_ordermanagement.OrderManagement_JobManagement_Service";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status SetOrderState(::grpc::ClientContext* context, const ::grpc_ordermanagement::Request_SetOrderState& request, ::grpc_ordermanagement::Reply_SetOrderState* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::grpc_ordermanagement::Reply_SetOrderState>> AsyncSetOrderState(::grpc::ClientContext* context, const ::grpc_ordermanagement::Request_SetOrderState& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::grpc_ordermanagement::Reply_SetOrderState>>(AsyncSetOrderStateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::grpc_ordermanagement::Reply_SetOrderState>> PrepareAsyncSetOrderState(::grpc::ClientContext* context, const ::grpc_ordermanagement::Request_SetOrderState& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::grpc_ordermanagement::Reply_SetOrderState>>(PrepareAsyncSetOrderStateRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void SetOrderState(::grpc::ClientContext* context, const ::grpc_ordermanagement::Request_SetOrderState* request, ::grpc_ordermanagement::Reply_SetOrderState* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void SetOrderState(::grpc::ClientContext* context, const ::grpc_ordermanagement::Request_SetOrderState* request, ::grpc_ordermanagement::Reply_SetOrderState* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void SetOrderState(::grpc::ClientContext* context, const ::grpc_ordermanagement::Request_SetOrderState* request, ::grpc_ordermanagement::Reply_SetOrderState* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::grpc_ordermanagement::Reply_SetOrderState>* AsyncSetOrderStateRaw(::grpc::ClientContext* context, const ::grpc_ordermanagement::Request_SetOrderState& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::grpc_ordermanagement::Reply_SetOrderState>* PrepareAsyncSetOrderStateRaw(::grpc::ClientContext* context, const ::grpc_ordermanagement::Request_SetOrderState& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status SetOrderState(::grpc::ClientContext* context, const ::grpc_ordermanagement::Request_SetOrderState& request, ::grpc_ordermanagement::Reply_SetOrderState* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::grpc_ordermanagement::Reply_SetOrderState>> AsyncSetOrderState(::grpc::ClientContext* context, const ::grpc_ordermanagement::Request_SetOrderState& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::grpc_ordermanagement::Reply_SetOrderState>>(AsyncSetOrderStateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::grpc_ordermanagement::Reply_SetOrderState>> PrepareAsyncSetOrderState(::grpc::ClientContext* context, const ::grpc_ordermanagement::Request_SetOrderState& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::grpc_ordermanagement::Reply_SetOrderState>>(PrepareAsyncSetOrderStateRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void SetOrderState(::grpc::ClientContext* context, const ::grpc_ordermanagement::Request_SetOrderState* request, ::grpc_ordermanagement::Reply_SetOrderState* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void SetOrderState(::grpc::ClientContext* context, const ::grpc_ordermanagement::Request_SetOrderState* request, ::grpc_ordermanagement::Reply_SetOrderState* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void SetOrderState(::grpc::ClientContext* context, const ::grpc_ordermanagement::Request_SetOrderState* request, ::grpc_ordermanagement::Reply_SetOrderState* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::grpc_ordermanagement::Reply_SetOrderState>* AsyncSetOrderStateRaw(::grpc::ClientContext* context, const ::grpc_ordermanagement::Request_SetOrderState& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::grpc_ordermanagement::Reply_SetOrderState>* PrepareAsyncSetOrderStateRaw(::grpc::ClientContext* context, const ::grpc_ordermanagement::Request_SetOrderState& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_SetOrderState_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status SetOrderState(::grpc::ServerContext* context, const ::grpc_ordermanagement::Request_SetOrderState* request, ::grpc_ordermanagement::Reply_SetOrderState* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_SetOrderState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SetOrderState() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_SetOrderState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetOrderState(::grpc::ServerContext* /*context*/, const ::grpc_ordermanagement::Request_SetOrderState* /*request*/, ::grpc_ordermanagement::Reply_SetOrderState* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSetOrderState(::grpc::ServerContext* context, ::grpc_ordermanagement::Request_SetOrderState* request, ::grpc::ServerAsyncResponseWriter< ::grpc_ordermanagement::Reply_SetOrderState>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_SetOrderState<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_SetOrderState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_SetOrderState() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc_ordermanagement::Request_SetOrderState, ::grpc_ordermanagement::Reply_SetOrderState>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc_ordermanagement::Request_SetOrderState* request, ::grpc_ordermanagement::Reply_SetOrderState* response) { return this->SetOrderState(context, request, response); }));}
    void SetMessageAllocatorFor_SetOrderState(
        ::grpc::experimental::MessageAllocator< ::grpc_ordermanagement::Request_SetOrderState, ::grpc_ordermanagement::Reply_SetOrderState>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::grpc_ordermanagement::Request_SetOrderState, ::grpc_ordermanagement::Reply_SetOrderState>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_SetOrderState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetOrderState(::grpc::ServerContext* /*context*/, const ::grpc_ordermanagement::Request_SetOrderState* /*request*/, ::grpc_ordermanagement::Reply_SetOrderState* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* SetOrderState(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc_ordermanagement::Request_SetOrderState* /*request*/, ::grpc_ordermanagement::Reply_SetOrderState* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* SetOrderState(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc_ordermanagement::Request_SetOrderState* /*request*/, ::grpc_ordermanagement::Reply_SetOrderState* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_SetOrderState<Service > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_SetOrderState<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_SetOrderState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SetOrderState() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_SetOrderState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetOrderState(::grpc::ServerContext* /*context*/, const ::grpc_ordermanagement::Request_SetOrderState* /*request*/, ::grpc_ordermanagement::Reply_SetOrderState* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_SetOrderState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SetOrderState() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_SetOrderState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetOrderState(::grpc::ServerContext* /*context*/, const ::grpc_ordermanagement::Request_SetOrderState* /*request*/, ::grpc_ordermanagement::Reply_SetOrderState* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSetOrderState(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_SetOrderState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_SetOrderState() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SetOrderState(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_SetOrderState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetOrderState(::grpc::ServerContext* /*context*/, const ::grpc_ordermanagement::Request_SetOrderState* /*request*/, ::grpc_ordermanagement::Reply_SetOrderState* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* SetOrderState(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* SetOrderState(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SetOrderState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SetOrderState() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::grpc_ordermanagement::Request_SetOrderState, ::grpc_ordermanagement::Reply_SetOrderState>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::grpc_ordermanagement::Request_SetOrderState, ::grpc_ordermanagement::Reply_SetOrderState>* streamer) {
                       return this->StreamedSetOrderState(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SetOrderState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SetOrderState(::grpc::ServerContext* /*context*/, const ::grpc_ordermanagement::Request_SetOrderState* /*request*/, ::grpc_ordermanagement::Reply_SetOrderState* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSetOrderState(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::grpc_ordermanagement::Request_SetOrderState,::grpc_ordermanagement::Reply_SetOrderState>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_SetOrderState<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_SetOrderState<Service > StreamedService;
};

}  // namespace grpc_ordermanagement


#endif  // GRPC_ordermanagement_5fjobmanagement_2eproto__INCLUDED
