// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: ordermanagement_jobmanagement.proto

#include "ordermanagement_jobmanagement.pb.h"
#include "ordermanagement_jobmanagement.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace grpc_ordermanagement {

static const char* OrderManagement_JobManagement_Service_method_names[] = {
  "/grpc_ordermanagement.OrderManagement_JobManagement_Service/SetOrderState",
};

std::unique_ptr< OrderManagement_JobManagement_Service::Stub> OrderManagement_JobManagement_Service::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< OrderManagement_JobManagement_Service::Stub> stub(new OrderManagement_JobManagement_Service::Stub(channel));
  return stub;
}

OrderManagement_JobManagement_Service::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_SetOrderState_(OrderManagement_JobManagement_Service_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status OrderManagement_JobManagement_Service::Stub::SetOrderState(::grpc::ClientContext* context, const ::grpc_ordermanagement::Request_SetOrderState& request, ::grpc_ordermanagement::Reply_SetOrderState* response) {
  return ::grpc::internal::BlockingUnaryCall< ::grpc_ordermanagement::Request_SetOrderState, ::grpc_ordermanagement::Reply_SetOrderState, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetOrderState_, context, request, response);
}

void OrderManagement_JobManagement_Service::Stub::experimental_async::SetOrderState(::grpc::ClientContext* context, const ::grpc_ordermanagement::Request_SetOrderState* request, ::grpc_ordermanagement::Reply_SetOrderState* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::grpc_ordermanagement::Request_SetOrderState, ::grpc_ordermanagement::Reply_SetOrderState, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetOrderState_, context, request, response, std::move(f));
}

void OrderManagement_JobManagement_Service::Stub::experimental_async::SetOrderState(::grpc::ClientContext* context, const ::grpc_ordermanagement::Request_SetOrderState* request, ::grpc_ordermanagement::Reply_SetOrderState* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetOrderState_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::grpc_ordermanagement::Reply_SetOrderState>* OrderManagement_JobManagement_Service::Stub::PrepareAsyncSetOrderStateRaw(::grpc::ClientContext* context, const ::grpc_ordermanagement::Request_SetOrderState& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::grpc_ordermanagement::Reply_SetOrderState, ::grpc_ordermanagement::Request_SetOrderState, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetOrderState_, context, request);
}

::grpc::ClientAsyncResponseReader< ::grpc_ordermanagement::Reply_SetOrderState>* OrderManagement_JobManagement_Service::Stub::AsyncSetOrderStateRaw(::grpc::ClientContext* context, const ::grpc_ordermanagement::Request_SetOrderState& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetOrderStateRaw(context, request, cq);
  result->StartCall();
  return result;
}

OrderManagement_JobManagement_Service::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      OrderManagement_JobManagement_Service_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< OrderManagement_JobManagement_Service::Service, ::grpc_ordermanagement::Request_SetOrderState, ::grpc_ordermanagement::Reply_SetOrderState, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](OrderManagement_JobManagement_Service::Service* service,
             ::grpc::ServerContext* ctx,
             const ::grpc_ordermanagement::Request_SetOrderState* req,
             ::grpc_ordermanagement::Reply_SetOrderState* resp) {
               return service->SetOrderState(ctx, req, resp);
             }, this)));
}

OrderManagement_JobManagement_Service::Service::~Service() {
}

::grpc::Status OrderManagement_JobManagement_Service::Service::SetOrderState(::grpc::ServerContext* context, const ::grpc_ordermanagement::Request_SetOrderState* request, ::grpc_ordermanagement::Reply_SetOrderState* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace grpc_ordermanagement

