// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: dbmanagement_ordermanagement.proto
#ifndef GRPC_dbmanagement_5fordermanagement_2eproto__INCLUDED
#define GRPC_dbmanagement_5fordermanagement_2eproto__INCLUDED

#include "dbmanagement_ordermanagement.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc_dbmanagement {

class DBManagement_OrderManagement_Service final {
 public:
  static constexpr char const* service_full_name() {
    return "grpc_dbmanagement.DBManagement_OrderManagement_Service";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Insert(::grpc::ClientContext* context, const ::grpc_dbmanagement::Request_Insert& request, ::grpc_dbmanagement::Reply_Insert* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::grpc_dbmanagement::Reply_Insert>> AsyncInsert(::grpc::ClientContext* context, const ::grpc_dbmanagement::Request_Insert& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::grpc_dbmanagement::Reply_Insert>>(AsyncInsertRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::grpc_dbmanagement::Reply_Insert>> PrepareAsyncInsert(::grpc::ClientContext* context, const ::grpc_dbmanagement::Request_Insert& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::grpc_dbmanagement::Reply_Insert>>(PrepareAsyncInsertRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void Insert(::grpc::ClientContext* context, const ::grpc_dbmanagement::Request_Insert* request, ::grpc_dbmanagement::Reply_Insert* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void Insert(::grpc::ClientContext* context, const ::grpc_dbmanagement::Request_Insert* request, ::grpc_dbmanagement::Reply_Insert* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void Insert(::grpc::ClientContext* context, const ::grpc_dbmanagement::Request_Insert* request, ::grpc_dbmanagement::Reply_Insert* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::grpc_dbmanagement::Reply_Insert>* AsyncInsertRaw(::grpc::ClientContext* context, const ::grpc_dbmanagement::Request_Insert& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::grpc_dbmanagement::Reply_Insert>* PrepareAsyncInsertRaw(::grpc::ClientContext* context, const ::grpc_dbmanagement::Request_Insert& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status Insert(::grpc::ClientContext* context, const ::grpc_dbmanagement::Request_Insert& request, ::grpc_dbmanagement::Reply_Insert* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::grpc_dbmanagement::Reply_Insert>> AsyncInsert(::grpc::ClientContext* context, const ::grpc_dbmanagement::Request_Insert& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::grpc_dbmanagement::Reply_Insert>>(AsyncInsertRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::grpc_dbmanagement::Reply_Insert>> PrepareAsyncInsert(::grpc::ClientContext* context, const ::grpc_dbmanagement::Request_Insert& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::grpc_dbmanagement::Reply_Insert>>(PrepareAsyncInsertRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void Insert(::grpc::ClientContext* context, const ::grpc_dbmanagement::Request_Insert* request, ::grpc_dbmanagement::Reply_Insert* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void Insert(::grpc::ClientContext* context, const ::grpc_dbmanagement::Request_Insert* request, ::grpc_dbmanagement::Reply_Insert* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void Insert(::grpc::ClientContext* context, const ::grpc_dbmanagement::Request_Insert* request, ::grpc_dbmanagement::Reply_Insert* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::grpc_dbmanagement::Reply_Insert>* AsyncInsertRaw(::grpc::ClientContext* context, const ::grpc_dbmanagement::Request_Insert& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::grpc_dbmanagement::Reply_Insert>* PrepareAsyncInsertRaw(::grpc::ClientContext* context, const ::grpc_dbmanagement::Request_Insert& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Insert_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Insert(::grpc::ServerContext* context, const ::grpc_dbmanagement::Request_Insert* request, ::grpc_dbmanagement::Reply_Insert* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Insert : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Insert() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Insert() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Insert(::grpc::ServerContext* /*context*/, const ::grpc_dbmanagement::Request_Insert* /*request*/, ::grpc_dbmanagement::Reply_Insert* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestInsert(::grpc::ServerContext* context, ::grpc_dbmanagement::Request_Insert* request, ::grpc::ServerAsyncResponseWriter< ::grpc_dbmanagement::Reply_Insert>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Insert<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_Insert : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_Insert() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc_dbmanagement::Request_Insert, ::grpc_dbmanagement::Reply_Insert>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc_dbmanagement::Request_Insert* request, ::grpc_dbmanagement::Reply_Insert* response) { return this->Insert(context, request, response); }));}
    void SetMessageAllocatorFor_Insert(
        ::grpc::experimental::MessageAllocator< ::grpc_dbmanagement::Request_Insert, ::grpc_dbmanagement::Reply_Insert>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::grpc_dbmanagement::Request_Insert, ::grpc_dbmanagement::Reply_Insert>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_Insert() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Insert(::grpc::ServerContext* /*context*/, const ::grpc_dbmanagement::Request_Insert* /*request*/, ::grpc_dbmanagement::Reply_Insert* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* Insert(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc_dbmanagement::Request_Insert* /*request*/, ::grpc_dbmanagement::Reply_Insert* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* Insert(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc_dbmanagement::Request_Insert* /*request*/, ::grpc_dbmanagement::Reply_Insert* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_Insert<Service > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_Insert<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Insert : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Insert() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Insert() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Insert(::grpc::ServerContext* /*context*/, const ::grpc_dbmanagement::Request_Insert* /*request*/, ::grpc_dbmanagement::Reply_Insert* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Insert : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Insert() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Insert() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Insert(::grpc::ServerContext* /*context*/, const ::grpc_dbmanagement::Request_Insert* /*request*/, ::grpc_dbmanagement::Reply_Insert* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestInsert(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_Insert : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_Insert() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Insert(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_Insert() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Insert(::grpc::ServerContext* /*context*/, const ::grpc_dbmanagement::Request_Insert* /*request*/, ::grpc_dbmanagement::Reply_Insert* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* Insert(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* Insert(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Insert : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Insert() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::grpc_dbmanagement::Request_Insert, ::grpc_dbmanagement::Reply_Insert>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::grpc_dbmanagement::Request_Insert, ::grpc_dbmanagement::Reply_Insert>* streamer) {
                       return this->StreamedInsert(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Insert() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Insert(::grpc::ServerContext* /*context*/, const ::grpc_dbmanagement::Request_Insert* /*request*/, ::grpc_dbmanagement::Reply_Insert* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedInsert(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::grpc_dbmanagement::Request_Insert,::grpc_dbmanagement::Reply_Insert>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Insert<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Insert<Service > StreamedService;
};

}  // namespace grpc_dbmanagement


#endif  // GRPC_dbmanagement_5fordermanagement_2eproto__INCLUDED
