// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: route_planner.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_route_5fplanner_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_route_5fplanner_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3014000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3014000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_route_5fplanner_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_route_5fplanner_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_route_5fplanner_2eproto;
namespace route_planner {
class Car_order;
class Car_orderDefaultTypeInternal;
extern Car_orderDefaultTypeInternal _Car_order_default_instance_;
class Reply;
class ReplyDefaultTypeInternal;
extern ReplyDefaultTypeInternal _Reply_default_instance_;
class Request;
class RequestDefaultTypeInternal;
extern RequestDefaultTypeInternal _Request_default_instance_;
}  // namespace route_planner
PROTOBUF_NAMESPACE_OPEN
template<> ::route_planner::Car_order* Arena::CreateMaybeMessage<::route_planner::Car_order>(Arena*);
template<> ::route_planner::Reply* Arena::CreateMaybeMessage<::route_planner::Reply>(Arena*);
template<> ::route_planner::Request* Arena::CreateMaybeMessage<::route_planner::Request>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace route_planner {

enum Car_order_Car : int {
  Car_order_Car_CAR_RUN = 0,
  Car_order_Car_CAR_STOP = 1,
  Car_order_Car_CAR_LEFT = 2,
  Car_order_Car_CAR_RIGHT = 3,
  Car_order_Car_Car_order_Car_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  Car_order_Car_Car_order_Car_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool Car_order_Car_IsValid(int value);
constexpr Car_order_Car Car_order_Car_Car_MIN = Car_order_Car_CAR_RUN;
constexpr Car_order_Car Car_order_Car_Car_MAX = Car_order_Car_CAR_RIGHT;
constexpr int Car_order_Car_Car_ARRAYSIZE = Car_order_Car_Car_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Car_order_Car_descriptor();
template<typename T>
inline const std::string& Car_order_Car_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Car_order_Car>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Car_order_Car_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Car_order_Car_descriptor(), enum_t_value);
}
inline bool Car_order_Car_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, Car_order_Car* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Car_order_Car>(
    Car_order_Car_descriptor(), name, value);
}
// ===================================================================

class Request PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:route_planner.Request) */ {
 public:
  inline Request() : Request(nullptr) {}
  virtual ~Request();

  Request(const Request& from);
  Request(Request&& from) noexcept
    : Request() {
    *this = ::std::move(from);
  }

  inline Request& operator=(const Request& from) {
    CopyFrom(from);
    return *this;
  }
  inline Request& operator=(Request&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Request& default_instance();

  static inline const Request* internal_default_instance() {
    return reinterpret_cast<const Request*>(
               &_Request_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Request& a, Request& b) {
    a.Swap(&b);
  }
  inline void Swap(Request* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Request* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Request* New() const final {
    return CreateMaybeMessage<Request>(nullptr);
  }

  Request* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Request>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Request& from);
  void MergeFrom(const Request& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Request* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "route_planner.Request";
  }
  protected:
  explicit Request(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_route_5fplanner_2eproto);
    return ::descriptor_table_route_5fplanner_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStartIdFieldNumber = 1,
    kEndIdFieldNumber = 2,
  };
  // int32 start_id = 1;
  void clear_start_id();
  ::PROTOBUF_NAMESPACE_ID::int32 start_id() const;
  void set_start_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_start_id() const;
  void _internal_set_start_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 end_id = 2;
  void clear_end_id();
  ::PROTOBUF_NAMESPACE_ID::int32 end_id() const;
  void set_end_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_end_id() const;
  void _internal_set_end_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:route_planner.Request)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::int32 start_id_;
  ::PROTOBUF_NAMESPACE_ID::int32 end_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_route_5fplanner_2eproto;
};
// -------------------------------------------------------------------

class Reply PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:route_planner.Reply) */ {
 public:
  inline Reply() : Reply(nullptr) {}
  virtual ~Reply();

  Reply(const Reply& from);
  Reply(Reply&& from) noexcept
    : Reply() {
    *this = ::std::move(from);
  }

  inline Reply& operator=(const Reply& from) {
    CopyFrom(from);
    return *this;
  }
  inline Reply& operator=(Reply&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Reply& default_instance();

  static inline const Reply* internal_default_instance() {
    return reinterpret_cast<const Reply*>(
               &_Reply_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Reply& a, Reply& b) {
    a.Swap(&b);
  }
  inline void Swap(Reply* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Reply* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Reply* New() const final {
    return CreateMaybeMessage<Reply>(nullptr);
  }

  Reply* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Reply>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Reply& from);
  void MergeFrom(const Reply& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Reply* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "route_planner.Reply";
  }
  protected:
  explicit Reply(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_route_5fplanner_2eproto);
    return ::descriptor_table_route_5fplanner_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIdsFieldNumber = 1,
  };
  // repeated int32 ids = 1;
  int ids_size() const;
  private:
  int _internal_ids_size() const;
  public:
  void clear_ids();
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_ids(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >&
      _internal_ids() const;
  void _internal_add_ids(::PROTOBUF_NAMESPACE_ID::int32 value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >*
      _internal_mutable_ids();
  public:
  ::PROTOBUF_NAMESPACE_ID::int32 ids(int index) const;
  void set_ids(int index, ::PROTOBUF_NAMESPACE_ID::int32 value);
  void add_ids(::PROTOBUF_NAMESPACE_ID::int32 value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >&
      ids() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >*
      mutable_ids();

  // @@protoc_insertion_point(class_scope:route_planner.Reply)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 > ids_;
  mutable std::atomic<int> _ids_cached_byte_size_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_route_5fplanner_2eproto;
};
// -------------------------------------------------------------------

class Car_order PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:route_planner.Car_order) */ {
 public:
  inline Car_order() : Car_order(nullptr) {}
  virtual ~Car_order();

  Car_order(const Car_order& from);
  Car_order(Car_order&& from) noexcept
    : Car_order() {
    *this = ::std::move(from);
  }

  inline Car_order& operator=(const Car_order& from) {
    CopyFrom(from);
    return *this;
  }
  inline Car_order& operator=(Car_order&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Car_order& default_instance();

  static inline const Car_order* internal_default_instance() {
    return reinterpret_cast<const Car_order*>(
               &_Car_order_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Car_order& a, Car_order& b) {
    a.Swap(&b);
  }
  inline void Swap(Car_order* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Car_order* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Car_order* New() const final {
    return CreateMaybeMessage<Car_order>(nullptr);
  }

  Car_order* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Car_order>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Car_order& from);
  void MergeFrom(const Car_order& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Car_order* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "route_planner.Car_order";
  }
  protected:
  explicit Car_order(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_route_5fplanner_2eproto);
    return ::descriptor_table_route_5fplanner_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef Car_order_Car Car;
  static constexpr Car CAR_RUN =
    Car_order_Car_CAR_RUN;
  static constexpr Car CAR_STOP =
    Car_order_Car_CAR_STOP;
  static constexpr Car CAR_LEFT =
    Car_order_Car_CAR_LEFT;
  static constexpr Car CAR_RIGHT =
    Car_order_Car_CAR_RIGHT;
  static inline bool Car_IsValid(int value) {
    return Car_order_Car_IsValid(value);
  }
  static constexpr Car Car_MIN =
    Car_order_Car_Car_MIN;
  static constexpr Car Car_MAX =
    Car_order_Car_Car_MAX;
  static constexpr int Car_ARRAYSIZE =
    Car_order_Car_Car_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  Car_descriptor() {
    return Car_order_Car_descriptor();
  }
  template<typename T>
  static inline const std::string& Car_Name(T enum_t_value) {
    static_assert(::std::is_same<T, Car>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function Car_Name.");
    return Car_order_Car_Name(enum_t_value);
  }
  static inline bool Car_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      Car* value) {
    return Car_order_Car_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kCarFieldNumber = 1,
  };
  // .route_planner.Car_order.Car car = 1;
  void clear_car();
  ::route_planner::Car_order_Car car() const;
  void set_car(::route_planner::Car_order_Car value);
  private:
  ::route_planner::Car_order_Car _internal_car() const;
  void _internal_set_car(::route_planner::Car_order_Car value);
  public:

  // @@protoc_insertion_point(class_scope:route_planner.Car_order)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  int car_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_route_5fplanner_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Request

// int32 start_id = 1;
inline void Request::clear_start_id() {
  start_id_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Request::_internal_start_id() const {
  return start_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Request::start_id() const {
  // @@protoc_insertion_point(field_get:route_planner.Request.start_id)
  return _internal_start_id();
}
inline void Request::_internal_set_start_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  start_id_ = value;
}
inline void Request::set_start_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_start_id(value);
  // @@protoc_insertion_point(field_set:route_planner.Request.start_id)
}

// int32 end_id = 2;
inline void Request::clear_end_id() {
  end_id_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Request::_internal_end_id() const {
  return end_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Request::end_id() const {
  // @@protoc_insertion_point(field_get:route_planner.Request.end_id)
  return _internal_end_id();
}
inline void Request::_internal_set_end_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  end_id_ = value;
}
inline void Request::set_end_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_end_id(value);
  // @@protoc_insertion_point(field_set:route_planner.Request.end_id)
}

// -------------------------------------------------------------------

// Reply

// repeated int32 ids = 1;
inline int Reply::_internal_ids_size() const {
  return ids_.size();
}
inline int Reply::ids_size() const {
  return _internal_ids_size();
}
inline void Reply::clear_ids() {
  ids_.Clear();
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Reply::_internal_ids(int index) const {
  return ids_.Get(index);
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Reply::ids(int index) const {
  // @@protoc_insertion_point(field_get:route_planner.Reply.ids)
  return _internal_ids(index);
}
inline void Reply::set_ids(int index, ::PROTOBUF_NAMESPACE_ID::int32 value) {
  ids_.Set(index, value);
  // @@protoc_insertion_point(field_set:route_planner.Reply.ids)
}
inline void Reply::_internal_add_ids(::PROTOBUF_NAMESPACE_ID::int32 value) {
  ids_.Add(value);
}
inline void Reply::add_ids(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_add_ids(value);
  // @@protoc_insertion_point(field_add:route_planner.Reply.ids)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >&
Reply::_internal_ids() const {
  return ids_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >&
Reply::ids() const {
  // @@protoc_insertion_point(field_list:route_planner.Reply.ids)
  return _internal_ids();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >*
Reply::_internal_mutable_ids() {
  return &ids_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >*
Reply::mutable_ids() {
  // @@protoc_insertion_point(field_mutable_list:route_planner.Reply.ids)
  return _internal_mutable_ids();
}

// -------------------------------------------------------------------

// Car_order

// .route_planner.Car_order.Car car = 1;
inline void Car_order::clear_car() {
  car_ = 0;
}
inline ::route_planner::Car_order_Car Car_order::_internal_car() const {
  return static_cast< ::route_planner::Car_order_Car >(car_);
}
inline ::route_planner::Car_order_Car Car_order::car() const {
  // @@protoc_insertion_point(field_get:route_planner.Car_order.car)
  return _internal_car();
}
inline void Car_order::_internal_set_car(::route_planner::Car_order_Car value) {
  
  car_ = value;
}
inline void Car_order::set_car(::route_planner::Car_order_Car value) {
  _internal_set_car(value);
  // @@protoc_insertion_point(field_set:route_planner.Car_order.car)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace route_planner

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::route_planner::Car_order_Car> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::route_planner::Car_order_Car>() {
  return ::route_planner::Car_order_Car_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_route_5fplanner_2eproto
