// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: route_planner.proto

#include "route_planner.pb.h"
#include "route_planner.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace route_planner {

static const char* RoutePlanner_method_names[] = {
  "/route_planner.RoutePlanner/SendRequest",
};

std::unique_ptr< RoutePlanner::Stub> RoutePlanner::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< RoutePlanner::Stub> stub(new RoutePlanner::Stub(channel));
  return stub;
}

RoutePlanner::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_SendRequest_(RoutePlanner_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status RoutePlanner::Stub::SendRequest(::grpc::ClientContext* context, const ::route_planner::Request& request, ::route_planner::Reply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::route_planner::Request, ::route_planner::Reply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendRequest_, context, request, response);
}

void RoutePlanner::Stub::experimental_async::SendRequest(::grpc::ClientContext* context, const ::route_planner::Request* request, ::route_planner::Reply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::route_planner::Request, ::route_planner::Reply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendRequest_, context, request, response, std::move(f));
}

void RoutePlanner::Stub::experimental_async::SendRequest(::grpc::ClientContext* context, const ::route_planner::Request* request, ::route_planner::Reply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendRequest_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::route_planner::Reply>* RoutePlanner::Stub::PrepareAsyncSendRequestRaw(::grpc::ClientContext* context, const ::route_planner::Request& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::route_planner::Reply, ::route_planner::Request, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendRequest_, context, request);
}

::grpc::ClientAsyncResponseReader< ::route_planner::Reply>* RoutePlanner::Stub::AsyncSendRequestRaw(::grpc::ClientContext* context, const ::route_planner::Request& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendRequestRaw(context, request, cq);
  result->StartCall();
  return result;
}

RoutePlanner::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RoutePlanner_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RoutePlanner::Service, ::route_planner::Request, ::route_planner::Reply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RoutePlanner::Service* service,
             ::grpc::ServerContext* ctx,
             const ::route_planner::Request* req,
             ::route_planner::Reply* resp) {
               return service->SendRequest(ctx, req, resp);
             }, this)));
}

RoutePlanner::Service::~Service() {
}

::grpc::Status RoutePlanner::Service::SendRequest(::grpc::ServerContext* context, const ::route_planner::Request* request, ::route_planner::Reply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace route_planner

